### ISSUE TITLE
docker-compose on flagportal / flagportal-revenge

### ISSUE THREAD

**Issue by TheVellichor** [Social-Engineering-Experts/SEETF-2022-Public#1]
there's no docker-compose file, but three different Dockerfile's, I'm attempting to simply build them and line them up together so far.

Any advice on how to do it properly? Thanks!! (attempting to follow writeups and build the challenges)

**Comment by zeyu2001** [comment]
Hi @TheVellichor, so sorry for the delayed response.

We will not be publishing the docker-compose files in this repository as some of them contain sensitive information pertaining to the final infrastructure setup (it is slightly different). However, I have kept a copy of the original docker-compose files for this challenge in my own repository [here](https://github.com/zeyu2001/My-CTF-Challenges/tree/main/SEETF-2022/web/flagportal-revenge).
